browser=chrome
grid.enabled=false
metrics.enabled=true
flaky.enabled=true
slack.enabled=true
video.enabled=false
devtools.enabled=false
gridUrl=http://localhost:4444/wd/hub
run.mode=local
grid.url=http://localhost:4444
headless=false
base.url=https://www.google.com