# Environment
env=prod

# Application
base.url=https://www.google.com

# Browser
browser=chrome
headless=false

# Timeouts
implicit.wait=10
page.load.timeout=30
slack.enabled=true

run.mode=local
grid.url=http://localhost:4444


# Trend
trend.enabled=true
trend.history.count=5
trend.fail.on.regression=false

# Flaky detection
flaky.enabled=false
flaky.history.count=5
flaky.threshold=0.2

notification.enabled=false

