# =============================
# Screenshot & Attachments
# =============================

report.screenshot.enabled=true
report.pageSource.enabled=true
report.consoleLogs.enabled=true
report.video.enabled=false

# =============================
# Allure
# =============================

allure.environment.enabled=true

# =============================
# Slack
# =============================

slack.enabled=true
slack.webhook.url=https://hooks.slack.com/services/YOUR/WEBHOOK
slack.notify.onFailure=true